# Generated by Django 4.2.3 on 2023-08-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miaplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidadDeLibros', models.IntegerField()),
            ],
        ),
    ]
